#!/bin/bash

SHADERS_DIR="$HOME/reshade-shaders/Shaders"
TEXTURES_DIR="$HOME/reshade-shaders/Textures"

killall -9 sober Sober 2>/dev/null

rm -rf ~/.var/app/org.vinegarhq.Sober/cache/sober/nv

flatpak run \
  --env=VKBASALT_SHADER_PATH="$SHADERS_DIR" \
  --env=VKBASALT_TEXTURE_PATH="$TEXTURES_DIR" \
  --env=ENABLE_VKBASALT=1 \
  --env=__GL_YIELD=NOTHING \
  --env=__GL_MaxFramesAllowed=1 \
  --env=vulkan_disable_fast_etc2=1 \
  org.vinegarhq.Sober
