# 🍷 VineShade vkBasalt Config

depthCapture = off
copyDepthBuffer = off

effects = cas:clarity

# These filenames must match the ones in your ~/reshade-shaders/Shaders folder
cas = CAS.fx
clarity = Clarity.fx
