# 🍷 VineShade vkBasalt Config

depthCapture = off
copyDepthBuffer = off

effects = effect:effect

# These filenames must match the ones in your ~/reshade-shaders/Shaders folder
effect = effect.fx
effect = effect.fx
